import Head from 'next/head'
import { useState, FormEvent } from 'react'
import { useAppDispatch, useAppSelector } from '@/store/hooks'
import { User, authUser, logout } from '@/store/session'
import { RootState } from '@/store/store'
// import Image from 'next/image'
// import styles from '@/styles/Home.module.css'

export default function Home() {
  const dispatch = useAppDispatch()
  const user: User | null = useAppSelector((state: RootState) => state.session.user)
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')

  const handleSubmit = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault()

    dispatch(authUser({ email, password }))
  }

  return (
    <>
      <Head>
        <title>next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      {
        user ? (
          <div>
            <button onClick={() => {dispatch(logout())}}>Logout</button>
          </div>
        ) : (
          <div>
            <form onSubmit={handleSubmit}>
              <input
                type='email'
                value={email}
                onChange={(e) => setEmail(e.target.value)}
              />
              <input
                type='password'
                value={password}
                onChange={e => setPassword(e.target.value)}
              />
              <button type='submit'>Submit</button>
            </form>
          </div>
        )
      }
    </>
  )
}
